cms/urls.py
from django.urls import path

from . import views

app_name = 'cms'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('signup/', views.UserCreate.as_view(), name='signup'),
    path('user/<int:pk>/update/', views.UserUpdate.as_view(), name='user_update'),
    path('user/<int:pk>/', views.UserDetail.as_view(), name='user_detail'),
    path('mypage/<int:pk>/', views.MyPage.as_view(), name='mypage'),
    path('project/create/', views.ProjectCreate.as_view(), name='project_create'),
    path('project/welcome/', views.project_welcome, name='project_welcome'),
    path('project/<int:pk>/', views.ProjectDetail.as_view(), name='project_detail'),
    path('project/<int:pk>/update/', views.ProjectUpdate.as_view(), name='project_update'),
    #path('project/<int:pk>/delete/', views.ProjectDelete.as_view(), name='project_delete'),
    path('project/<int:pk>/dashboard/', views.ProjectDashboard.as_view(), name='dashboard'),
    #path('project/<int:pk>/dashboard/commit/', views.ProjectDashboardCommit.as_view(), name='dashboard_commit'),
    #path('project/<int:pk>/dashboard/plan/', views.ProjectDashboardPlan.as_view(), name='dashboard_plan'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cms.urls')),
]

cms/models.py
from django.contrib.auth.base_user import (
    AbstractBaseUser, BaseUserManager,
)
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.core.mail import send_mail
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


# User-related
class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Create and save a user with the given email and password.
        """
        if not email:
            raise ValueError('Users must have an email address')
        user = self.model(
            email=self.normalize_email(email),
            **extra_fields,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class AbstractUser(AbstractBaseUser, PermissionsMixin):

    username_validator = UnicodeUsernameValidator()
    username = models.CharField(
        _('username'),
        max_length=150,
        unique=True,
        help_text=_('Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.'),
        validators=[username_validator],
        error_messages={
            'unique': _("A user with that username already exists."),
        },
    )

    first_name = models.CharField(_('first name'), max_length=150, blank=True)
    last_name = models.CharField(_('last name'), max_length=150, blank=True)

    email = models.EmailField(_('email address'), unique=True)

    GRADE_CHOICES = [
        ('B1', '学士1年'),
        ('B2', '学士2年'),
        ('B3', '学士3年'),
        ('B4', '学士4年'),
        ('Mr', '修士'),
        ('Dr', '博士'),
    ]
    grade = models.CharField(_('学年'), max_length=3, choices=GRADE_CHOICES, blank=True)
    twitter = models.CharField(_('Twitter'), max_length=50, blank=True)
    github = models.CharField(_('GitHub'), max_length=50, blank=True)
    bio = models.TextField(
        _('自己紹介'),
        help_text=_('必須。140字以内。'),
        max_length=140,
        blank=True,
    )

    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')
        abstract = True

    def __str__(self):
        return self.email

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)


class User(AbstractUser):
    class Meta(AbstractUser.Meta):
        swappable = "AUTH_USER_MODEL"


# Project-related
class Tag(models.Model):
    name = models.CharField(_('タグ'), max_length=50)

    def __str__(self):
        if hasattr(self, 'note_count'):
            return f'{self.name}({self.note_count})'
        return self.name


class Project(models.Model):
    name = models.CharField(_('プロジェクト名'), max_length=50, unique=True)

    # tag = models.ManyToManyField(Tag)
    members = models.ManyToManyField(User, through='ProjectUserRelation')

    twitter = models.CharField(_('Twitter'), max_length=50, blank=True)
    github = models.CharField(_('GitHub'), max_length=50, blank=True)
    product_url = models.URLField(
        _('プロダクトURL'),
        help_text=_('必須。まだ完成していない場合ピッチ資料のGoogle Driveリンクなどを与えること。')
    )
    description = models.TextField(
        _('プロダクト説明'),
        help_text=_('必須。140字以内。'),
        max_length=140
    )

    STATE_CHOICES = [
        ('0', 'Dead'),
        ('1', 'Idea'),
        ('2', 'Prototyping'),
        ('3', 'Launched'),
        ('4', 'User-acquired'),
    ]
    state = models.CharField(
        _('プロジェクトのレベル'),
        max_length=2,
        choices=STATE_CHOICES,
        default='1',
    )

    does_accept_application = models.BooleanField(_('メンバーを募集しているかどうか'), default=False)
    application = models.TextField(_('応募方法'), blank=True)

    is_public = models.BooleanField(_('公開可能かどうか'), default=True)
    created_at = models.DateTimeField(_('プロジェクト作成日'), default=timezone.now)
    updated_at = models.DateTimeField(_('プロジェクト更新日'), auto_now=True)

    def __str__(self):
        return self.name


class ProjectUserRelation(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    joined_at = models.DateTimeField(default=timezone.now)


class ProjectLog(models.Model):
    title = models.CharField(_('ログタイトル'), max_length=50)
    text = models.TextField(_('ログ内容'))
    achievement = models.PositiveSmallIntegerField(
        _('達成度'),
        validators = [MinValueValidator(0), MaxValueValidator(10)],
        help_text=_('必須。10段階で達成度を評価してください。'),
    )
    created_at = models.DateTimeField(_('ログ作成日'), default=timezone.now)
    project = models.ForeignKey(Project, on_delete=models.DO_NOTHING)


class ProjectPlan(models.Model):
    content = models.CharField(_('プラン内容'), max_length=255)
    date = models.DateField(_('プラン期日'))
    project = models.ForeignKey(Project, on_delete=models.DO_NOTHING)

cms/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.utils.text import capfirst
from django.utils.translation import gettext_lazy as _

from .backends import EmailAuthBackend
from .models import Project

UserModel = get_user_model()


class EmailAuthenticationForm(forms.Form):
    email = forms.EmailField(max_length=254,
                             widget=forms.TextInput(attrs={'autofocus': True, 'class': 'input', }))
    password = forms.CharField(label=_("Password"), strip=False,
                               widget=forms.PasswordInput(attrs={'class': 'input', }))
    error_messages = {
        'invalid_login': "メールアドレス または パスワードに誤りがあります。",
        'inactive': _("This account is inactive."),
    }

    def __init__(self, request=None, *args, **kwargs):
        self.request = request
        self.user_cache = None
        super().__init__(*args, **kwargs)

        # Set the label for the "email" field.
        self.email_field = UserModel._meta.get_field("email")
        if self.fields['email'].label is None:
            self.fields['email'].label = capfirst(self.email_field.verbose_name)

    def clean(self):
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')

        if email is not None and password:
            self.user_cache = EmailAuthBackend().authenticate(self.request, email=email, password=password)
            if self.user_cache is None:
                raise forms.ValidationError(
                    self.error_messages['invalid_login'],
                    code='invalid_login',
                    params={'email': self.email_field.verbose_name})
            else:
                self.confirm_login_allowed(self.user_cache)

        return self.cleaned_data

    def confirm_login_allowed(self, user):
        if not user.is_active:
            raise forms.ValidationError(self.error_messages['inactive'], code='inactive')

    def get_user_id(self):
        if self.user_cache:
            return self.user_cache.id
        return None

    def get_user(self):
        return self.user_cache


class UserCreateForm(UserCreationForm):

    class Meta:
        model = UserModel
        fields = ('email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'input'


class UserUpdateForm(forms.ModelForm):

    class Meta:
        model = UserModel
        fields = ('username', 'first_name', 'last_name', 'email', 'grade', 'github', 'twitter')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'input'


class ProjectCreateForm(forms.ModelForm):

    class Meta:
        model = Project
        fields = ('name', 'product_url', 'description', 'is_public', 'twitter', 'github', 'does_accept_application', 'application')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs['class'] = 'input'
        self.fields['description'].widget.attrs['class'] = 'textarea'
        self.fields['product_url'].widget.attrs['class'] = 'input'
        self.fields['twitter'].widget.attrs['class'] = 'input'
        self.fields['github'].widget.attrs['class'] = 'input'
        self.fields['application'].widget.attrs['class'] = 'textarea'


class ProjectUpdateForm(forms.ModelForm):

    class Meta:
        model = Project
        fields = ('name', 'product_url', 'description', 'is_public', 'twitter', 'github', 'does_accept_application', 'application')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs['class'] = 'input'
        self.fields['description'].widget.attrs['class'] = 'textarea'
        self.fields['product_url'].widget.attrs['class'] = 'input'
        self.fields['twitter'].widget.attrs['class'] = 'input'
        self.fields['github'].widget.attrs['class'] = 'input'
        self.fields['application'].widget.attrs['class'] = 'textarea'

cms/views.py
from django.shortcuts import render, resolve_url
from django.contrib.auth import login, get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.contrib.auth.views import (
    LoginView, LogoutView,
)
from django.views.generic.detail import DetailView
from django.views.generic.edit import (
    CreateView, UpdateView, DeleteView,
)

from .forms import (
    EmailAuthenticationForm, UserCreateForm, UserUpdateForm,
    ProjectCreateForm, ProjectUpdateForm,
)
from .models import (
    Project,
)
from .mixins import (
    OnlyYouMixin, OnlyProjectMemberMixin,
)

UserModel = get_user_model()


def index(request):
    return render(request, 'cms/index.html', {})


def about(request):
    return render(request, 'cms/about.html', {})


def contact(request):
    return render(request, 'cms/contact.html', {})


class Login(LoginView):
    form_class = EmailAuthenticationForm
    template_name = 'registration/login.html'


class Logout(LogoutView):
    template_name = 'cms/index.html'


class UserCreate(CreateView):
    form_class = UserCreateForm
    template_name = 'registration/signup.html'
    success_url = reverse_lazy('index')

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        self.object = user
        return HttpResponseRedirect(self.get_success_url())


class UserDetail(DetailView):
    model = UserModel
    template_name = 'user/user_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['pk'] = self.kwargs['pk']
        return context


class UserUpdate(OnlyYouMixin, UpdateView):
    model = UserModel
    form_class = UserUpdateForm
    template_name = 'user/user_update.html'

    def get_success_url(self):
        return resolve_url('cms:user_detail', pk=self.kwargs['pk'])


class MyPage(LoginRequiredMixin, OnlyYouMixin, DetailView):
    model = UserModel
    template_name = 'user/mypage.html'


class ProjectCreate(LoginRequiredMixin, CreateView):
    model = Project
    form_class = ProjectCreateForm
    template_name = 'project/project_create.html'
    success_url = reverse_lazy('cms:project_welcome')

    def form_valid(self, form):
        project = form.save(commit=False)
        project.members.add(self.request.user)
        project.save()
        return HttpResponseRedirect(self.get_success_url())


@login_required
def project_welcome(request):
    return render(request, 'project/project_welcome.html', {})


class ProjectUpdate(LoginRequiredMixin, OnlyProjectMemberMixin, UpdateView):
    model = Project
    template_name = 'project/project_update.html'
    form_class = ProjectUpdateForm

    def get_success_url(self):
        return resolve_url('cms:project_detail', pk=self.kwargs['pk'])


class ProjectDetail(DetailView):
    model = Project
    template_name = 'project/project_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['pk'] = self.kwargs['pk']
        return context


class ProjectDashboard(LoginRequiredMixin, OnlyProjectMemberMixin, DetailView):
    model = Project
    template_name = 'project/dashboard.html'

cms/templates/user/mypage.html
{% extends 'cms/base.html' %}

{% block title %}My Page | {% endblock %}

{% block content %}
<section class="hero is-small is-link is-bold">
    <div class="hero-body">
        <div class="container has-text-centered">
            <h1 class="title">My Page</h1>
            <h2 class="subtitle">@{{ user.username }}</h2>
        </div>
    </div>
</section>
<section class="section">
    <div class="container">
        <div class="tile is-ancestor">
            <div class="tile is-parent is-6">
                <article class="tile is-child box">
                    <p class="title">Ongoing Project</p>
                    <p class="subtitle">進行中のプロジェクト</p>
                    <div class="content">
                        <ul>
                            {% for project in user.project_set.all %}
                            <li class="box">
                                <a href="{% url 'cms:dashboard' project.pk %}" class="has-text-grey">
                                    <p class="title is-6">{{ project.name }}</p>
                                    <progress class="progress is-small is-info" value="{{ project.state }}" max="4"></progress>
                                </a>
                            </li>
                            {% endfor %}
                            <li class="button is-info is-light">
                                <a href="{% url 'cms:project_create' %}">
                                    <span class="icon is-small is-left"><i class="fas fa-plus"></i></span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </article>
            </div>
            <div class="tile is-parent is-6">
                <article class="tile is-child box">
                    <p class="title">Settings</p>
                    <p class="subtitle">設定</p>
                    <div class="content">
                        <hr class="">
                        <a href="{% url 'cms:user_detail' user.pk %}" class="">
                            <p class="title is-4">Check Your Portfolio</p>
                            <p class="subtitle is-6">プロフィールを確認する</p>
                        </a>
                        <hr>
                        <a href="{% url 'cms:user_update' user.pk %}" class="is-grey">
                            <p class="title is-4">Change Your Portfolio</p>
                            <p class="subtitle is-6">プロフィールを変更する</p>
                        </a>
                        <hr>
                    </div>
                </article>
            </div>
        </div>
    </div>
</section>
{% endblock %}

cms/templates/user/user_detail.html
{% extends 'cms/base.html' %}

{% block title %}{{ user.last_name }} {{ user.first_name }} | {% endblock %}

{% block content %}
<section class="hero is-link is-bold">
    <div class="hero-body">
        <div class="container">
            <div class="media">
                <div class="media-left">
                    <figure class="image is-64x64 is-left">
                        <img class="is-rounded" src="https://bulma.io/images/placeholders/128x128.png">
                    </figure>
                </div>
                <div class="media-content">
                    <h1 class="title">
                        {{ user.last_name }} {{ user.first_name }}
                    </h1>
                    <h2 class="subtitle">
                        @{{ user.username }}
                    </h2>
                    {% if user.pk == request.user.pk %}
                    <a href="{% url 'cms:user_update' user.pk %}">
                        <button class="button is-small is-info is-inverted is-outlined">
                            <span class="icon is-small is-left"><i class="fas fa-user-edit"></i></span>
                            <strong>プロフィールを追加する</strong>
                        </button>
                    </a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</section>
<section class="section">
    <div class="container">
        <div class="level">
            <div class="level-left">
                {% if user.twitter %}
                <div class="level-item">
                    <div class="tags has-addons">
                        <span class="tag"><span class="icon is-small is-left"><i class="fab fa-twitter"></i></span></span>
                        <span class="tag is-dark"><a class="has-text-white" href="https://twitter.com/{{ user.twitter }}" target="_blank">@{{ user.twitter }}</a></span>
                    </div>
                </div>
                {% endif %}
                {% if user.github %}
                <div class="level-item">
                    <div class="tags has-addons">
                        <span class="tag"><span class="icon is-small is-left"><i class="fab fa-github"></i></span></span>
                        <span class="tag is-dark"><a class="has-text-white" href="https://github.com/{{ user.github }}" target="_blank">@{{ user.github }}</a></span>
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
        {% if user.bio %}
            <p>{{ user.bio }}</p>
        {% elif user.pk == request.user.pk %}
            <a href="{% url 'cms:user_update' user.pk %}">
                <button class="button is-small is-danger is-outlined">
                    <span class="icon is-small is-left"><i class="fas fa-user-edit"></i></span>
                    <strong>自己紹介を追加する</strong>
                </button>
            </a>
        {% else %}
            <p>プロフィールは追加されておりません。</p>
        {% endif %}
        <hr>
        <div class="is-mobile box">
            <h1 class="title is-4">参加中のプロジェクト</h1>
            <h2 class="subtitle is-6">ongoing project</h2>
            <div class="tile is-ancestor">
                {% for project in user.project_set.all %}
                <div class="tile is-parent is-3">
                    <article class="box tile is-child">
                        <p class="level-item title is-5">{{ project.name }}</p>
                        <progress class="level-item progress is-small is-link" value="{{ project.state }}" max="4"></progress>
                        <a href="{% url 'cms:project_detail' project.pk %}" class="is-grey">
                            <button class="button is-small is-link is-right">詳細を見る</button>
                        </a>
                    </article>
                </div>
                {% endfor %}
            </div>
        </div>
</section>
{% endblock %}

cms/templates/user/user_update.html
{% extends 'cms/base.html' %}

{% block title %}{{ user.username }} | {% endblock %}

{% block content %}
<section class="section">
    <div class="container is-mobile">
        <h1 class="title is-4">ユーザー情報の更新</h1>
        <h2 class="subtitle is-6">Update your information</h2>
        <hr>
        <form method="post" action="">
            {% csrf_token %}
            <div class="field">
                <label class="label">ユーザーネーム</label>
                <div class="control has-icons-left">
                    {{ form.username }}
                    <span class="icon is-small is-left">@</span>
                </div>
                <p class="help has-text-grey">@を含めないでください</p>
            </div>
            <div class="field">
                <label class="label">姓</label>
                <div class="control has-icons-left">
                    {{ form.last_name }}
                    <span class="icon is-small is-left"><i class="fas fa-user"></i></span>
                </div>
            </div>
            <div class="field">
                <label class="label">名</label>
                <div class="control has-icons-left">
                    {{ form.first_name }}
                    <span class="icon is-small is-left"><i class="fas fa-user"></i></span>
                </div>
            </div>
            <div class="field">
                <label class="label">学年</label>
                <div class="control has-icons-left">
                    {{ form.grade }}
                </div>
            </div>
            <div class="field">
                <label class="label">メールアドレス</label>
                <div class="control has-icons-left">
                    {{ form.email }}
                    <span class="icon is-small is-left"><i class="fas fa-envelope"></i></span>
                </div>
            </div>
            <div class="field">
                <label class="label">Twitter</label>
                <div class="control has-icons-left">
                    {{ form.twitter }}
                    <span class="icon is-small is-left">@</span>
                    <p class="help has-text-grey">@を含めないでください</p>
                </div>
            </div>
            <div class="field">
                <label class="label">GitHub</label>
                <div class="control has-icons-left">
                    {{ form.github }}
                    <span class="icon is-small is-left">@</span>
                    <p class="help has-text-grey">@を含めないでください</p>
                </div>
            </div>
            <div class="field">
                <p class="control">
                    <input type="submit" value="保存" class="button is-success">
                    <input type="hidden" name="next" value="{{ next }}" >
                </p>
            </div>
        </form>
    </div>
</section>
{% endblock %}